name: reusable
on:
  workflow_call:
    inputs:
      differentParam:
        required: false
        type: string
      customFlavor:
        required: false
        type: string

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo \"flavor=${{ inputs.customFlavor }}\" 